/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ImageProps } from "./components/hover-image/types";
import { StepBoxState } from "./components/step-box/utility";
export { ImageProps } from "./components/hover-image/types";
export { StepBoxState } from "./components/step-box/utility";
export namespace Components {
    interface HoverImage {
        "backgroundColor"?: string;
        "height"?: number;
        "main": ImageProps;
        "secondary"?: ImageProps;
        "width"?: number;
    }
    interface StepBox {
        "btnBacground"?: string;
        "btnColor"?: string;
        "btnHover"?: string;
        "iconText"?: string;
    }
}
export interface StepBoxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLStepBoxElement;
}
declare global {
    interface HTMLHoverImageElement extends Components.HoverImage, HTMLStencilElement {
    }
    var HTMLHoverImageElement: {
        prototype: HTMLHoverImageElement;
        new (): HTMLHoverImageElement;
    };
    interface HTMLStepBoxElement extends Components.StepBox, HTMLStencilElement {
    }
    var HTMLStepBoxElement: {
        prototype: HTMLStepBoxElement;
        new (): HTMLStepBoxElement;
    };
    interface HTMLElementTagNameMap {
        "hover-image": HTMLHoverImageElement;
        "step-box": HTMLStepBoxElement;
    }
}
declare namespace LocalJSX {
    interface HoverImage {
        "backgroundColor"?: string;
        "height"?: number;
        "main"?: ImageProps;
        "secondary"?: ImageProps;
        "width"?: number;
    }
    interface StepBox {
        "btnBacground"?: string;
        "btnColor"?: string;
        "btnHover"?: string;
        "iconText"?: string;
        "onStepBoxStateChange"?: (event: StepBoxCustomEvent<StepBoxState>) => void;
    }
    interface IntrinsicElements {
        "hover-image": HoverImage;
        "step-box": StepBox;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "hover-image": LocalJSX.HoverImage & JSXBase.HTMLAttributes<HTMLHoverImageElement>;
            "step-box": LocalJSX.StepBox & JSXBase.HTMLAttributes<HTMLStepBoxElement>;
        }
    }
}
